### ISSUE TITLE
Normalize tables?

### ISSUE THREAD

**Issue by joecomerisnotavailable** [crypdick/police-traffic-stop-explorer#7]
I feel like it might just make more work for us, but the table's not 3NF right now--officer gender, race, etc are attributes of the officer, so maybe it's worth making an officer table? Same with county_name, county_fips, etc.

On one hand it reflects well on us in the final report to have made the effort, otoh it probably just makes writing the queries more complex on the back end.

**Comment by joecomerisnotavailable** [comment]
Suggested ER Diagram in my branch

**Comment by joecomerisnotavailable** [comment]
Although it occurs to me that officer_age will change over the course of the data. Maybe that needs to stay in the stops table?

**Comment by joecomerisnotavailable** [comment]
officer_ids are duplicated. See data_readme in my branch for notes. Will try to address later.

**Comment by joecomerisnotavailable** [comment]
We'll have to keep officer_age and officer_rank in the stops table, but I'm writing a function to make the officers table to contain maximal information about race and gender for each officer_id. I've pushed the sql, but it doesn't run yet. I've been playing with all this stuff in a separate database called Open_Policing just so as to not botch the clean data in the Stanford_Open DB.

**Comment by crypdick** [comment]
Good idea, I think that when we make the app live we should set the db permissions to read-only to avoid any surprised-- I don't know much about sanitizing inputs so we should try everything we can to avoid fuckery. as for normalizing, honestly, I think the most important thing is getting the viz looking good. I doubt we're going to get points taken off for not using 3NF. I think using 3NF would be handy if we want to viz the cop-centric data, but I think we should make our lives easier for now and limit the scope of this project to just the geospatial info. I can't think of any interesting questions that we would ask using the cop fields (heatmap of cop ages? heatmap of cop ranks? kinda boring imo).

**Comment by crypdick** [comment]
looks like we're using a flat table for now, can reopen if we change our minds
