### ISSUE TITLE
write python wrapper functions to query psql

### ISSUE THREAD

**Issue by crypdick** [crypdick/police-traffic-stop-explorer#8]
use psycopg to query psql and return the query. 

@duffrind do you have a preference for data format for the front-end stuff? Python objects (Pandas df, numpy arrays, python built-ins) OR would you prefer to write the results to disk (JSON, CSVs)?

**Comment by duffrind** [comment]
Whatever is easiest for you. I can use Google's protobuf if you use python
data types or read the csv directly so it doesn't matter to me.

**Comment by crypdick** [comment]
Ok. I think that the outputs are going to be pretty small (just a vector, right?) so even if the app gets a lot of traffic we can avoid writing to disk and just do everything in RAM. 

aside: does D3.js render everything client-side or server-side? I'm wondering if having lots of people rendering heatmaps would be hard on the server.

**Comment by duffrind** [comment]
Client side rendering and it is surprisingly efficient even on mobile
devices

**Comment by duffrind** [comment]
Switched to Folium (server-side rendering) still pretty fast.

Uses python datatypes.

**Comment by crypdick** [comment]
solved with 44d0140
