### ISSUE TITLE
init directories on flask server

### ISSUE THREAD

**Issue by crypdick** [crypdick/police-traffic-stop-explorer#9]
I don't know what the directory tree for this repo should look like so that the webserver works properly. @duffrind if you could set up the empty directories where we should set up our python scripts that would be great. also, we need to clone this repo onto our flask server with the right permissions, if we haven't already done so.

**Comment by joecomerisnotavailable** [comment]
From Dr. Gillman's email:

"I'm sorry for the lack of documentation.

Your directory structure needs to mimic that of /var/www/FlaskApp. There are examples of Hello World web pages in /var/www/FlaskApp and /var/www/PythonApp.

Your root directory (and its subdirectory) needs to be called /var/www/YourAppName. Please give me your app name and I'll create the directory with permission for your group.

Here are tutorials:
http://flask.pocoo.org/
https://www.theodo.fr/blog/2017/03/developping-a-flask-web-app-with-a-postresql-database-making-all-the-possible-errors/"

I don't know if that first part was the directory tree you were talking about.

Have we given Gillman our app name to get the permissions?

**Comment by duffrind** [comment]
EDIT: I misunderstood the post. Can you have him create the directory PoliceStops and then give us permissions.

**Comment by crypdick** [comment]
solved with 8ca0357
